### ISSUE TITLE
Columns names lost after DrImpute(matrix)

### ISSUE THREAD

**Issue by HichamAffia** [ikwak2/DrImpute#3]
I I'm trying to use DrImpute to get a better clustering with the Seurat package.
So I impute de dropout events prior to creating the seurat object. 

But after preprocessing the data, at the DrImpute() step I lose my colnames,  that are required to be able to create my Seurat object.

Can I assume that the colnames of the outpute of the fonction are in the same order as those in the input file and just reassign them?

Many thanks for the help!

**Comment by ikwak2** [comment]
Yes, output columns will have same order.
I may need to update DrImpute function later. 
Thank you!
